dbt_big_query_project:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{env_var('PROJECT_NAME')}}"
      dataset: "{{env_var('DATASET_NAME')}}"
      threads: 4
      priority: interactive
      job_execution_timeout_seconds: 1
      keyfile: "{{env_var('KEYFILE')}}"